from .compiler import SlideCanvas, SlideCompiler
from .font_metrics import FontMetrics
from .components import ComponentRegistry
from .layouts import BlueprintLibrary
from .models import (
    CompilerError,
    ContentItem,
    DeckValidationError,
    DesignDNA,
    DesignValidationError,
    LayoutError,
    LayoutMetrics,
    LayoutPlan,
    Palette,
    Region,
    ShapeLanguage,
    SlideFrame,
    Source,
    TextOverflowError,
    TextSpan,
    Typography,
    ValidationIssue,
    ValidationReport,
    contrast_ratio,
    required_layout_families,
)
from .recipe import (
    AdaptiveLayoutSelector,
    DeckRecipe,
    LayoutChoice,
    RecipeAssembler,
    SlideRecipe,
)

__all__ = [
    "BlueprintLibrary",
    "CompilerError",
    "ComponentRegistry",
    "ContentItem",
    "DeckValidationError",
    "DesignDNA",
    "DesignValidationError",
    "DeckRecipe",
    "FontMetrics",
    "LayoutError",
    "LayoutChoice",
    "LayoutMetrics",
    "LayoutPlan",
    "Palette",
    "Region",
    "RecipeAssembler",
    "ShapeLanguage",
    "SlideCanvas",
    "SlideCompiler",
    "SlideRecipe",
    "SlideFrame",
    "Source",
    "TextOverflowError",
    "TextSpan",
    "Typography",
    "ValidationIssue",
    "ValidationReport",
    "AdaptiveLayoutSelector",
    "contrast_ratio",
    "required_layout_families",
]
